version: '3.8'

services:
  webproxy:
    image: padirodrigo/nginx:0.0
    ports:
      - "8080:8080"
    networks:
      - wordpress
    depends_on:
      webserver:
        condition: service_healthy
    container_name: webproxy

  webserver:
    image: wordpress:latest
    volumes:
      - app:/var/www/html
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wordpress
    depends_on:
      database:
        condition: service_healthy
    container_name: webserver
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5

  database:
    image: mysql:5.7
    volumes:
      - my:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root  
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: root 
    networks:
      - wordpress
    container_name: database
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  app:
    name: app
  my:
    name: my

networks:
  wordpress:
    name: wordpress
