---
- name: Projeto Final ASA
  hosts: all
  become: yes

  tasks:
    - name: Configurar hostname
      hostname:
        name: server.rodrigo.padilha
      #tags: hostname

    - name: Atualizar pacotes
      apt:
        update_cache: yes

    - name: Instalar dependências
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg-agent
        state: present
      #tags: dependencies

    - name: Adicionar chave GPG docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      #tags: docker

    - name: Adicionar repositório docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      #tags: docker

    - name: Instalar Docker CE
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes
      #tags: docker

    - name: Adicionar usuário ansible ao grupo Docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
     #tags: docker

    - name: Baixar/instalar docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Copiar docker-compose.yml para VM
      copy:
        src: ./docker-compose.yml
        dest: /home/{{ ansible_user }}/docker-compose.yml
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Executando docker-compose up -d
      command: docker-compose up -d
      args:
        chdir: /home/{{ ansible_user }}
